### ISSUE TITLE
Converting from DragonBones(DB) to Darkest Dungeon

### ISSUE THREAD

**Issue by MonteePoke** [brachna/SpineConverter2.1.27#1]
Not really an issue. I think i managed to export project from DB to DD. Translation, rotation, scaling and meshes seems to work. To make rotation and meshes work i had to tweak spJsonReader a little (2 new lines and 1 altered).
![C1IY6rfWZb](https://user-images.githubusercontent.com/44632941/90383114-5dacc800-e088-11ea-92c5-febbe718ec9a.gif)
![N38qGtr9jO](https://user-images.githubusercontent.com/44632941/90383135-66050300-e088-11ea-8ecf-79f98b84bbb4.gif)

**Comment by MonteePoke** [comment]
A little update: i created a [guide](https://steamcommunity.com/sharedfiles/filedetails/?id=2200465472) on how to import and export to and from DragonBones. 
![Ya8lu6RH8h](https://user-images.githubusercontent.com/44632941/90428482-bbfb9a00-e0cc-11ea-980d-429a35fce876.gif)

**Comment by brachna** [comment]
Hello. Nice work!
Original idea was to make an importer/exporter for Blender COA-Tools, but author of the tool did not provide an api.
I was looking into DragonBones instead, but its Spine plugin was very bad at that time (summer 2019), it couldn't import its own exported file without errors. So that idea was dropped.
Glad that things have improved and people took the idea further.

**Comment by MonteePoke** [comment]
Hi again. 
I'm not sure, but i think DB still can't import back it's own exported files. I'll check it later.
For now i want to add you to Guide contributors, so if you can add me on Steam.
Also in order to make skins rotate and meshes work i had to tweak your spJsonReader.py a little. I was wondering if i should my own fork, create a pull request or just attach a [link ](https://steamcommunity.com/linkfilter/?url=https://drive.google.com/file/d/1AEbV3aWq04gslEuJrZBbB_YOU8Aol8u0/view?usp=sharing)to edited file like i did in my guide. 
Every change is commented with #todo. There is only 2 new lines and 1 altered.

**Comment by MonteePoke** [comment]
Tested exporting and importing back. It doesn't work unless you manually add "spine" : " " to .json. String just has to be not empty.

**Comment by brachna** [comment]
I checked your edits with diffchecker. You changed "ffd" key to "deform" and assume shear timelines. It's good that it helps with import/export for DB, but I don't believe that's how Spine 2.1.27 json structured. iirc deform and shear were introduced in 3.0, so maybe those are just quirks of DB Spine plugin. All my tests were done using linked SkeletonViewer, changing "ffd" to "deform" creates regression when viewing Abomination transformation file.
If you wish to fork then do so, this repo was made as an archive.
